
#ifndef INC_MEMCHCKR_VERSION_H
#define INC_MEMCHCKR_VERSION_H

#define MEMCK_VERSION_MAJOR    1
#define MEMCK_VERSION_MINOR_HI 0
#define MEMCK_VERSION_MINOR_LO 2
#define MEMCK_VERSION_PATCH    3

#endif
